sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true