sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

before_install:
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install && echo "zend_extension = xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && cd ..; fi
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
